version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "ghcr.io/lms-community/lyrionmusicserver"
    ignore:
      - dependency-name: "ghcr.io/lms-community/lyrionmusicserver"
        versions:
          - "*-dev"
          - "*-alpha*"
          - "*-beta*"
          - "*-rc*"
