services:
  lms:
    image: niklasdoerfler/squeezebox-media-server-docker
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/shm:/dev/shm
      - /etc/machine-id:/etc/machine-id
      - /run/user/$UID/pulse:/run/user/$UID/pulse
      - /var/lib/dbus:/var/lib/dbus
      - squeezebox:/config
      - /path/to/your/music:/music
    environment:
      - PULSE_SERVER=unix:/tmp/pulseaudio.socket
      - PULSE_COOKIE=/tmp/pulseaudio.cookie
      - WAVIN_BACKEND=pulse
    user: $UID
    ports:
      - "9000:9000"
      - "9090:9090"
      - "3483:3483"
      - "3483:3483/udp"
    restart: unless-stopped
    init: true

volumes:
  squeezebox:
